### ISSUE TITLE
mtgapi.com is changing

### ISSUE THREAD

**Issue by michaelcurry** [nessamurmur/mtgapi#2]
Hello, I am the creator of mtgapi.com and I wanted to let you know that mtgapi has been rewritten and has new documentation.  Please contact me at info@mtgapi.com and I can send you the new documentation.

These changes will be going live soon.

**Comment by nessamurmur** [comment]
:+1: I had surgery when you sent me this and totally missed it. Thanks. I'll be updating this soon so it's a little less simplistic. Thanks @michaelcurry!

**Comment by nessamurmur** [comment]
@michaelcurry I've updated the gem for the new endpoints. Please let me know if you notice anything else I'm missing that's new. Thanks!
